### ISSUE TITLE
Attempting to inject an unknown injection: 'service:scheduler'

### ISSUE THREAD

**Issue by mgebiesheuvel** [BBVAEngineering/ember-modal-service#13]
> Attempting to inject an unknown injection: 'service:scheduler'

Above error occur in v1.1.0 while trying to open a modal.

**Comment by josex2r** [comment]
Hi @mgebiesheuvel.

Have you installed all the npm packages after upgrading to `v1.1.0`?
The new version introduces de [ember-task-scheduler](https://github.com/BBVAEngineering/ember-task-scheduler) dependency in [model.js](https://github.com/BBVAEngineering/ember-modal-service/commit/eca45c942767fbe2e7d569c297a9833d365c1718#diff-e92d146b50af93193c9e4231908a65b6R28)

**Comment by mgebiesheuvel** [comment]
Why isn't that dependency added to the package.json?

**Comment by adrigzr** [comment]
Hi @mgebiesheuvel,

It is, indeed, in the `package.json`, but in the wrong section. It must be on `dependencies` and not on `devDependencies`. I will change it ASAP. 

Thank you!

**Comment by adrigzr** [comment]
#14
