### ISSUE TITLE
Custom modal name?

### ISSUE THREAD

**Issue by lougreenwood** [BBVAEngineering/ember-modal-service#22]
Hi, is it possible to customise the name used for the modal?

I like to store my modals in a nested directory structure (e.g: `modals/some-modal`). It seems that nested components is incompatible with the add-on?

**Comment by josex2r** [comment]
Yes, it could be possible but you have to place your "modals" inside your `components` directory.

You will have to `reopen` the `modal` model to edit the [`fullName` property](https://github.com/BBVAEngineering/ember-modal-service/blob/23150fa88c729c148acc220afcf6df93540d3777/addon/models/modal.js#L55) before loading the application (maybe in some initializer).

Something like this should work:

```js
// app/initializers/reopens.js
import { dasherize } from '@ember/string';
import Modal from 'ember-modal-service/models/modal';

Modal.reopen({
  fullname: computed('name', function() {
    this._super();
    const name = this.get('name');

    return `modals/${dasherize(name)}`
  }),
});

export default {
  name: 'reopen-modal',
  initialize: () => {}
};
```

**Comment by tleperou** [comment]
I confirm that works, just add `import { computed } from '@ember/object'` to make the snippet work.

**Comment by adrigzr** [comment]
Closing issue.

**Comment by lougreenwood** [comment]
Heh - what a coincidence, I only actually implemented this in my code this morning! Thanks
