### ISSUE TITLE
Default promise actions?

### ISSUE THREAD

**Issue by lougreenwood** [BBVAEngineering/ember-modal-service#23]
Hi,

I'm curious if there's anyway to set a default set of actions to be called for a single modal or for all modals.

For example, I'd like to add the `overflow: hidden` style to the `<body>` element when I open any modal and then remove the inline styling when I close the modal.

It seems that the obvious way to handle this is something like:

```
      this.get('modal').open('my-modal, { formModel: this.model }).then(
        document.getElementsByTagName("BODY")[0].setAttribute("style", "overflow: hidden"),
        function() {
          document.getElementsByTagName("BODY")[0].setAttribute("style", "overflow: visible");
        }
      );
```

But this means I now need to remember to add this to all calls to `modal.open`, which seems too fragile...

**Comment by josex2r** [comment]
You can use the `modal service` to handle this feature.
The service is in charge of opening the modals so it knows how many of them are opened. Checking the property `content` should do the work:

```js
// some controller/route/maybe application?
import { empty } from '@ember/object/computed';
import { inject as service } from '@ember/service';
import { observer } from '@ember/object';

{
  modal: service(),
  emptyModals: empty('modal.content'),
  onModalChanges: observer('emptyModals', function() {
    const overflow = this.get('emptyModals') ? 'visible' : 'hidden';
    document.querySelector('body').style.overflow = overflow;
  })
}
```

**Comment by lougreenwood** [comment]
Thanks, this works! 👍
