### ISSUE TITLE
ember-cli-babel 5.x has been deprecated

### ISSUE THREAD

**Issue by jandillmann** [BBVAEngineering/ember-modal-service#25]
When using ember-modal-service with Ember 3.3.0, I get the following deprecation message:     

    DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.1.10 located: ...

**Comment by SergeAstapov** [comment]
@jandillmann Looks like it was resolved in #26

**Comment by josex2r** [comment]
Hi, version `1.2.0` should have the fix.

**Comment by jandillmann** [comment]
Awesome :)
