### ISSUE TITLE
Resolve multiple arguments not working

### ISSUE THREAD

**Issue by edukun** [BBVAEngineering/ember-modal-service#85]
I have a modal with two text fields. After filling them up, when you click the YES
 button, I call the action "resolve" with two arguments containing the two texts. In the .then((text1, text2) => ..., text2 is always undefined.

I've debugged the service, and in resolve action, arguments are good. But the call to this.resolve(...arguments) fails, because the function resolve only takes first argument as data, the second one is label, so it is resolved as label and not passed to the .then function later.

![Captura de pantalla 2019-07-08 a las 10 05 35](https://user-images.githubusercontent.com/1574284/60793499-1d320980-a168-11e9-8d05-87b1fce1ea6f.png)

![Captura de pantalla 2019-07-08 a las 9 48 28](https://user-images.githubusercontent.com/1574284/60793509-215e2700-a168-11e9-9ccb-7b39dbdc09f8.png)

![Captura de pantalla 2019-07-08 a las 9 48 47](https://user-images.githubusercontent.com/1574284/60793510-215e2700-a168-11e9-8ade-4907adc9c057.png)

![Captura de pantalla 2019-07-08 a las 9 50 00](https://user-images.githubusercontent.com/1574284/60793511-215e2700-a168-11e9-8fec-53c5e1e209d2.png)

![Captura de pantalla 2019-07-08 a las 9 50 38](https://user-images.githubusercontent.com/1574284/60793512-215e2700-a168-11e9-8cda-d91ea00a8991.png)

**Comment by adrigzr** [comment]
Hi @edukun,

Modal use promises as protocol and promises can only be resolved with one value. Think of it as a return value. You can only return one value in a function. 

So, you can do something like this: 

`this.resolve({ text1: 'foo', text2: 'bar' });`

`modal.then(({ text1, text2 }) => { ... });`

**Comment by edukun** [comment]
Hi @adrigzr,

Thanks for your response. 

I based my code on the documentation:

You can pass any arguments you want the modal to be resolved / rejected with
`<button {{action "reject" "foo" "bar"}}>Close modal</button>`

I thought it would work right out of the box. I'll fork the project then.

Thanks!
