### ISSUE TITLE
Use requestAnimationFrame after transition check

### ISSUE THREAD

**Issue by josex2r** [BBVAEngineering/ember-modal-service#9]
This issue applies when #7 is merged.

Using `Ember.run` in [line 49 of `addon/utils/css-transitions/on-transition-end.js`](https://github.com/BBVAEngineering/ember-modal-service/pull/7/files/46841b02393de361e3123e86da891045e7141df4#diff-17cccd582190f52e90e49121de05f8a7R49) can cause a reflow if the callback code is using some DOM properties that forces reflow.

This can be fixed using `window.requestAnimationFrame`.

Remember to fix this when `requestAnimationFrame` addon its done and published.

**Comment by adrigzr** [comment]
#11 resolves this.
